# Generated by Django 2.2.6 on 2021-04-12 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.Wallet', verbose_name='Кошелек'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(verbose_name='Текущий баланс в рублях'),
        ),
    ]
